openapi: 3.1.0
info:
  title: 'Some API 2.0'
  version: 2.0.0-beta.22
security:
  -
    apiKey: []
paths:
  '/api/bookings/{id}':
    get:
      tags:
        - Booking
      operationId: Get Booking
      summary: 'Retrieves a Booking resource.'
      parameters:
        -
          name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: 'Booking resource response'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Default_bookings_overview'
        404:
          description: 'Resource not found'
  '/api/bookings/{id}/pay/session':
    put:
      tags:
        - Bookings
      operationId: Create Payment Session
      summary: 'Creates payment session'
      parameters:
        -
          name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: 'Session created'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/booking_pay_session_response'
        400:
          description: 'Invalid input'
        404:
          description: 'Resource not found'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/booking_pay_session_request'
        description: 'The updated Bookings resource'
components:
  schemas:
    Default_bookings_overview:
      type: object
      description: ''
      properties:
        id:
          readOnly: true
          type: integer
        uuid:
          type: string
          format: uuid
    'booking_pay_session_response':
      type: object
      description: ''
      properties:
        payment_id:
          type: string
        action:
          type: array
          items:
            type: string
    'booking_pay_session_request':
      type: object
      description: ''
      properties:
        return_url:
          type: string
        channel:
          type: string
          nullable: true
        is_native3d_secure:
          type: boolean
      required:
        - return_url
  securitySchemes:
    apiKey:
      type: apiKey
      in: header
      description: 'Value for the Authorization header'
      name: Authorization